name: pydis

channels:
    - astropy

dependencies:
    - python=3.4
    - astropy
    - scipy
    - matplotlib
    - numpy
    - pip:
        - sphinx-automodapi
        - numpydoc
        - sphinx-astropy
